### ISSUE TITLE
Centos 7 build kernel panics after first restart.

### ISSUE THREAD

**Issue by ChiperSoft** [kaorimatz/packer-templates#1]
Initial install runs, system restarts to run the provisioning scripts, and immediately kernel panics.

    VFS: Unable to mount root fs on unknown-block(0,0)

- Packer 0.8.2
- Vagrant 1.7.4
- Virtualbox 5.0.0

**Comment by kaorimatz** [comment]
Thank you for reporting the issue and sorry for the inconvenience.  The cause of the kernel panic is that there is no `initrd` line in `/boot/extlinux/extlinux.conf`. grubby-8.28-11.el7 has a bug that it doesn't insert `initrd` line into extlinux.conf when installing new kernel. I think we can avoid this issue by using grub2 instead of extlinux. The following change will achieve that. 

```diff
diff --git a/http/centos-7.0/anaconda-ks.cfg b/http/centos-7.0/anaconda-ks.cfg
index 904a23c..d9af3bd 100644
--- a/http/centos-7.0/anaconda-ks.cfg
+++ b/http/centos-7.0/anaconda-ks.cfg
@@ -10,7 +10,7 @@ user --name=vagrant --groups=vagrant --password=vagrant --plaintext
 zerombr
 clearpart --all --initlabel
 autopart --type=plain
-bootloader --extlinux --timeout=1
+bootloader --timeout=1

 %packages
 @core
```

I will commit this change after I test it on my environment.

**Comment by kaorimatz** [comment]
I pushed the change. If you still have issues please tell me. Thanks!

**Comment by ChiperSoft** [comment]
Working like a charm. Thanks!
